export * from './course-consumption/course-consumption.component';
export * from './organization/organization.component';
export * from './course-progress/course-progress.component';
export * from './usage-reports/usage-reports.component';
export * from './content-creation-statics/content-creation-statics.component';
export * from './city-wise-report/city-wise-report.component';
export * from './dept-city-wise-report/dept-city-wise-report.component';
export * from './content-dept-wise-report/content-dept-wise-report.component';
export * from './total-users/total-users.component';